[package]
name = "miden-processor"
version = "0.3.0"
description = "Miden VM processor"
authors = ["miden contributors"]
readme = "README.md"
license = "MIT"
repository = "https://github.com/0xPolygonMiden/miden-vm"
categories = ["emulators", "no-std"]
keywords = ["miden", "virtual-machine"]
edition = "2021"
rust-version = "1.62"

[lib]
bench = false
doctest = false

[features]
default = ["std"]
std = ["vm-core/std", "winterfell/std", "log/std"]

[dependencies]
log = "0.4.14"
vm-core = { package = "miden-core", path = "../core", version = "0.3", default-features = false }
winterfell = { package = "winter-prover", path = "../../winterfell/prover", default-features = false }

[dev-dependencies]
logtest = { version = "2.0", default-features = false  }
miden-assembly = { package = "miden-assembly", path = "../assembly", version = "0.3", default-features = false }
rand-utils = { version = "0.4.0", path = "../../winterfell/utils/rand", package = "winter-rand-utils" }
