[package]
name = "miden-prover"
version = "0.3.0"
description = "Miden VM prover"
authors = ["miden contributors"]
readme = "README.md"
license = "MIT"
repository = "https://github.com/0xPolygonMiden/miden-vm"
categories = ["cryptography", "emulators", "no-std"]
keywords = ["miden", "prover", "stark", "zkp"]
edition = "2021"
rust-version = "1.62"

[features]
concurrent = ["prover/concurrent", "std"]
default = ["std"]
std = ["air/std", "processor/std", "prover/std", "log/std", "vm-core/std"]

[dependencies]
air = { package = "miden-air", path = "../air", version = "0.3", default-features = false }
log = { version = "0.4", default-features = false }
processor = { package = "miden-processor", path = "../processor", version = "0.3", default-features = false }
prover = { package = "winter-prover", version = "0.4.0", default-features = false, path = "../../winterfell/prover" }
vm-core = { package = "miden-core", path = "../core", version = "0.3", default-features = false }
