[package]
name = "miden"
version = "0.3.0"
description="Miden virtual machine"
authors = ["miden contributors"]
readme="README.md"
license = "MIT"
repository = "https://github.com/0xPolygonMiden/miden-vm"
categories = ["cryptography", "emulators", "no-std"]
keywords = ["miden", "stark", "virtual-machine", "zkp"]
edition = "2021"
rust-version = "1.62"

[[bin]]
name = "miden"
path = "src/main.rs"
bench = false
doctest = false
required-features = ["executable"]

[lib]
name = "miden"
path = "src/lib.rs"
bench = false
doctest = false

[[bench]]
name = "program_compilation"
harness = false

[[bench]]
name = "program_execution"
harness = false

[features]
concurrent = ["prover/concurrent", "std"]
default = ["std"]
executable = ["crypto", "env_logger", "hex/std", "std", "serde/std", "serde_derive", "serde_json/std", "structopt", "winter-utils", "rustyline"]
std = ["air/std", "assembly/std", "log/std", "processor/std", "prover/std", "verifier/std", "vm-core/std"]

[dependencies]
air = { package = "miden-air", path = "../air", version = "0.3", default-features = false }
assembly = { package = "miden-assembly", path = "../assembly", version = "0.3", default-features = false }
crypto = { package = "winter-crypto", version = "0.4.2", default-features = false, optional = true }
env_logger = { version = "0.9", default-features = false, optional = true }
hex = { version = "0.4", optional = true }
log = { version = "0.4", default-features = false }
processor = { package = "miden-processor", path = "../processor", version = "0.3", default-features = false }
prover = { package = "miden-prover", path = "../prover", version = "0.3", default-features = false }
rustyline = { version = "10.0.0", default-features = false, optional = true}
serde = {version = "1.0.117", optional = true }
serde_derive = {version = "1.0.117", optional = true }
serde_json = {version = "1.0.59", optional = true }
stdlib = { package = "miden-stdlib", path = "../stdlib", version = "0.2", default-features = false }
structopt = { version = "0.3", default-features = false, optional = true }
verifier = { package = "miden-verifier", path = "../verifier", version = "0.3", default-features = false }
vm-core = { package = "miden-core", path = "../core", version = "0.3", default-features = false }
winter-utils = { package = "winter-utils", version = "0.4.0", optional = true, path = "../../winterfell/utils/core" }

[dev-dependencies]
blake3 = "1.3"
criterion = "0.4"
math = { package = "winter-math", version = "0.4.2", default-features = false }
num-bigint = "0.4"
proptest = "1.0.0"
rand-utils = { package = "winter-rand-utils", version = "0.4.2" }
sha2 = "0.10"
sha3 = "0.10"
test-case = "2.2.2"
